admin/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    url(r'^accounts/', include('djwarrant.urls', namespace='dw'))
]

djwarrant/urls.py
from django.contrib.auth import views as auth_views
from django.urls import re_path, path

from .views import ProfileView, UpdateProfileView, MySubscriptions,\
    AdminListUsers, AdminSubscriptions, LogoutView, SignUpView, InventoryView

from . import views

app_name = 'dw'

urlpatterns = (
    re_path(r'^login/$', auth_views.LoginView.as_view(
        template_name='warrant/login.html',
        redirect_authenticated_user=True), name='login'),
    re_path(r'^logout/$',
            LogoutView.as_view(template_name='warrant/logout.html'), name='logout'),
    re_path(r'^signup/$', SignUpView.as_view(), name='signup'),
    re_path(r'^password_reset/$',
            auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$',
            auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
    re_path(r'^profile/$', ProfileView.as_view(), name='profile'),
    re_path(r'^profile/update/$', UpdateProfileView.as_view(),
            name='update-profile'),
    re_path(r'^profile/subscriptions/$',
            MySubscriptions.as_view(), name='subscriptions'),
    #     re_path(r'^profile/storeinfo/$', views.storeinfo, name='storeinfo'),
    #     re_path(r'^profile/storeinfo/update-inventory',
    #             InventoryView.as_view(), name='update-inventory'),
    path('profile/account_verification',
         views.AccountVerificationView.as_view()),
    path('profile/account_verification/<slug:username>', views.AccountVerificationView.as_view(),
         name='account_verification'),
    re_path(r'^admin/cognito-users/$', AdminListUsers.as_view(),
            name='admin-cognito-users'),
    re_path(r'^admin/cognito-users/(?P<username>[-\w]+)$',
            AdminSubscriptions.as_view(), name='admin-cognito-user')
)

library/urls.py
from django.urls import path, re_path
from .views.books import browse, index, CreateBook, EditBook
from .views.pages import home

urlpatterns = (
    path('', home, name='index'),
    re_path(r'^books/$', index, name='book_index'),
    path('books/<slug:id>/edit', EditBook.as_view(), name="edit_book"),
    path('books/create', CreateBook.as_view(), name="create_book")
)

webapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    url(r'^accounts/', include('djwarrant.urls', namespace='dw'))
]

library/models.py
from django.db import models


class Store(models.Model):
    """
      A store in our system that provides mask.
    """
    id = models.UUIDField(primary_key=True)
    name = models.CharField(max_length=300)
    inventory = {
        "adult": models.IntegerField(),
        "children": models.IntegerField(),
    }
    address = models.CharField(max_length=300)

library/forms.py
from django import forms

# User defined forms here


class CreateBookForm(forms.Form):
    name = forms.CharField(max_length=500, required=True)
    year = forms.CharField(
        widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))
    author = forms.CharField(max_length=200, required=True)
    genre = forms.CharField(max_length=100, required=True)
    isbn = forms.CharField(max_length=25, required=True)

    def clean(self):
        book = super().clean()
        self.book = book

        return book

library/views/books.py
from django.views.generic import FormView, TemplateView
from library.utils.dynamo_helpers import create_book
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator
from django.conf import settings
import boto3
from library.forms import CreateBookForm
from django.shortcuts import resolve_url
from library.utils.dynamo_helpers import get_books, update_book, get_book_by_id_and_user
from django.views.generic.edit import UpdateView


def index(request):
    books = get_books(str(request.user.id))

    return render(request, 'library/books/index.html', {'books': books})


class CreateBook(FormView):
    template_name = 'library/books/create.html'
    form_class = CreateBookForm

    def get_success_url(self):
        return resolve_url('/')

    def form_valid(self, form):
        try:
            created_book = create_book(
                form.book['name'],
                form.book['year'],
                form.book['author'],
                form.book['genre'],
                form.book['isbn'],
                user_id=self.request.user.id)
        except Exception as e:
            print(e)
            form.errors['name'] = form.error_class(
                [f"We couldn't save this book. {e}"]
            )

            return self.form_invalid(form)

        return super().form_valid(form)


class EditBook(FormView):
    template_name = 'library/books/update.html'
    form_class = CreateBookForm

    def get_success_url(self):
        return resolve_url('/')

    def get_initial(self):
        book_id = str(self.kwargs['id'])
        user_id = str(self.request.user.id)

        book = get_book_by_id_and_user(id=book_id, user_id=user_id)

        return {
            'name': book['name'],
            'year': book['year'],
            'author': book['author'],
            'genre': book['genre'],
            'isbn': book['isbn']
        }

    def form_valid(self, form):
        try:
            updated_book = update_book(
                self.kwargs['id'],
                form.book['name'],
                form.book['year'],
                form.book['author'],
                form.book['genre'],
                form.book['isbn'],
                user_id=str(self.request.user.id)
            )
        except Exception as e:
            print(e)
            form.errors['name'] = form.error_class(
                [f"Failed to update book. Please try again in a few minutes."]
            )

            return self.form_invalid(form)

        return super().form_valid(form)


def browse(request):
    # Get access token
    client = boto3.client('cognito-identity',
                          region_name=settings.AWS_REGION)
    # Get credentials for authenticated user
    try:
        resp = client.get_id(IdentityPoolId=settings.COGNITO_IDENTITY_POOL,
                             Logins={
                                 'cognito-idp.'+settings.AWS_REGION+'.amazonaws.com/'+settings.COGNITO_USER_POOL_ID: request.session['ID_TOKEN']
                             })
        resp = client.get_credentials_for_identity(IdentityId=resp['IdentityId'],
                                                   Logins={
                                                       'cognito-idp.'+settings.AWS_REGION+'.amazonaws.com/'+settings.COGNITO_USER_POOL_ID: request.session['ID_TOKEN']
        })
    # Otherwise, get credential for unauthenticated user
    except:
        resp = client.get_id(IdentityPoolId=settings.COGNITO_IDENTITY_POOL)
        resp = client.get_credentials_for_identity(
            IdentityId=resp['IdentityId'])

    secretKey = resp['Credentials']['SecretKey']
    accessKey = resp['Credentials']['AccessKeyId']
    sessionToken = resp['Credentials']['SessionToken']

    client = boto3.client('dynamodb', aws_access_key_id=accessKey,
                          aws_secret_access_key=secretKey, aws_session_token=sessionToken,
                          region_name=settings.AWS_REGION)
    response = client.scan(TableName=settings.DYNAMODB_BOOKS)
    booklist = sorted(response['Items'], key=lambda k: int(k['id']['S']))
    paginator = Paginator(booklist, 20)

    page = request.GET.get('page')
    books = paginator.get_page(page)

    return render(request, 'browse.html', {'books': books})

library/views/pages.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse


def home(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('book_index'))

    return render(request, 'index.html')

library/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Slighty Smarter Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'browse' %}">Browse</a></li>
		  {% if user.is_authenticated %}
			<li>User: {{ user.get_username }}</li>
			<li><a href="{% url 'dw:profile'%}">My Profile</a></li>
			<li><a href="{% url 'dw:update-profile'%}">Edit Profile</a></li>
			<li><a href="{% url 'dw:logout'%}?next={{request.path}}">Logout</a></li>
		  {% else %}
			<li><a href="{% url 'dw:login'%}?next={{request.path}}">Login</a></li>
		  {% endif %} 
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
		{% block content %}{% endblock %}
		{% block pagination %}
		  {% if is_paginated %}
			<div class="pagination">
			  <span class="page-links">
				{% if page_obj.has_previous %}
				  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
				{% endif %}
				<span class="page-current">
				  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
				</span>
				{% if page_obj.has_next %}
				  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
				{% endif %}
			  </span>
			</div>
		  {% endif %}
		{% endblock %} 
	  </div>
    </div>
  </div>
</body>
</html>

library/templates/browse.html
{% extends "warrant/base.html" %}

{% block title %}
  <title>SSL | Slighty Smarter Library - Browse</title>
{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th>ISBN</th>
        </tr>
      {% for book in books %}
        <tr>
            <td>{{ book.id.S }}</td>
            <td>{{ book.title.S }}</td>
            <td>{{ book.author.S }}</td>
            <td>{{ book.genre.SS }}</td>
            <td>{{ book.isbn.N }}</td>
        </tr>
      {% endfor %}
    </table>
{% endblock %}

<!--
<div class="pagination">
    <span class="step-links">
        {% if books.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ books.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ books.number }} of {{ books.paginator.num_pages }}.
        </span>

        {% if books.has_next %}
            <a href="?page={{ books.next_page_number }}">next</a>
            <a href="?page={{ books.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
-->

library/templates/index.html
{% extends "warrant/base.html" %}
{% load static %}

{% block extra_css %}
	<link href="{% static 'css/home.css' %}" rel="stylesheet"/>
{% endblock extra_css %}

{% block title %}
  Home
{% endblock %}

{% block main_content %}
	<div class="bg-white container text-center">
		<img width="420px" src="{% static 'img/books.gif' %}" />
    <h1 class="text-center" style="margin-top: 1em"> <strong> Welcome to your Smart Library Management System! </strong> </h1>
    <h3>Click to <a href="{% url "dw:login" %}">Login</a> or <a href="{% url "dw:signup" %}">Sign Up</a>
	</div>
  {{ id }}
{% endblock %}

library/templates/register.html
{% extends 'warrant/base.html' %}

{% block title %} | Register {% endblock title %}

{% block main_content %}
<div id="tabs">
    <h1>Register</h1>

    <div id="register" class='tab'>
        <form method='post' class="form">
            {% csrf_token %}
            <table class="table">
            {{ form.as_table }}
            </table>
            <input type='submit' value='Register' />
        </form>
    </div>
</div>
{% endblock %}