admin/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    url(r'^accounts/', include('djwarrant.urls', namespace='dw'))
]

djwarrant/urls.py
from django.contrib.auth import views as auth_views
from django.urls import re_path, path

from .views import ProfileView, UpdateProfileView, MySubscriptions,\
    AdminListUsers, AdminSubscriptions, LogoutView, SignUpView, InventoryView

from . import views

app_name = 'dw'

urlpatterns = (
    re_path(r'^login/$', auth_views.LoginView.as_view(
        template_name='warrant/login.html',
        redirect_authenticated_user=True), name='login'),
    re_path(r'^logout/$',
            LogoutView.as_view(template_name='warrant/logout.html'), name='logout'),
    re_path(r'^signup/$', SignUpView.as_view(), name='signup'),
    re_path(r'^password_reset/$',
            auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$',
            auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
    re_path(r'^profile/$', ProfileView.as_view(), name='profile'),
    re_path(r'^profile/update/$', UpdateProfileView.as_view(),
            name='update-profile'),
    re_path(r'^profile/subscriptions/$',
            MySubscriptions.as_view(), name='subscriptions'),
    #     re_path(r'^profile/storeinfo/$', views.storeinfo, name='storeinfo'),
    #     re_path(r'^profile/storeinfo/update-inventory',
    #             InventoryView.as_view(), name='update-inventory'),
    path('profile/account_verification',
         views.AccountVerificationView.as_view()),
    path('profile/account_verification/<slug:username>', views.AccountVerificationView.as_view(),
         name='account_verification'),
    re_path(r'^admin/cognito-users/$', AdminListUsers.as_view(),
            name='admin-cognito-users'),
    re_path(r'^admin/cognito-users/(?P<username>[-\w]+)$',
            AdminSubscriptions.as_view(), name='admin-cognito-user')
)

webapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    url(r'^accounts/', include('djwarrant.urls', namespace='dw'))
]

djwarrant/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MaxValueValidator, MinValueValidator
from bootstrap_modal_forms.forms import BSModalForm
from .models import Store


class StoreForm(BSModalForm):
    class Meta:
        model = Store
        fields = ['adult_masks', 'children_masks']


class ProfileForm(forms.Form):
    name = forms.CharField(max_length=200, required=True)
    email = forms.EmailField(required=True)
    address = forms.CharField(max_length=200, required=False)
    # api_key = forms.CharField(max_length=200, required=False)
    # api_key_id = forms.CharField(max_length=200, required=False)


class APIKeySubscriptionForm(forms.Form):
    plan = forms.ChoiceField(required=True)

    def __init__(self, plans=[], users_plans=[], *args, **kwargs):
        self.base_fields['plan'].choices = [
            (p.get('id'), p.get('name')) for p in plans if not p.get('id') in users_plans]
        super(APIKeySubscriptionForm, self).__init__(*args, **kwargs)


class AccountVerificationForm(forms.Form):
    """Verifies a user to create their account"""
    username = forms.CharField()
    confirmation_code = forms.CharField(
        required=True, max_length=6, label="Verification Code")

    def clean(self):
        user = super(AccountVerificationForm, self).clean()
        self.user = user

        return user


class SignUpForm(forms.Form):
    """Specifies required information for user sign up"""
    username = forms.CharField(max_length=100, required=True)
    name = forms.CharField(max_length=200, required=True)
    email = forms.EmailField(required=True)
    library_name = forms.CharField(max_length=200, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    verify_password = forms.CharField(
        widget=forms.PasswordInput(), required=True)

    def clean(self):
        user = super(SignUpForm, self).clean()
        self.user = user

        if user.get('password') != user.get('verify_password'):
            self.errors['verify_password'] = \
                self.error_class(['Passwords do not match'])
            del self.user['password']

        del self.user['verify_password']

        return user

djwarrant/views.py
from django.shortcuts import render

# Create your views here.

djwarrant/views/profile.py
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url
try:
    from django.urls import reverse_lazy, reverse
except ImportError:
    from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, TemplateView
from django.contrib import messages
from django.contrib.auth.views import LogoutView as DJLogoutView
from django.conf import settings
from django.shortcuts import render
from djwarrant.utils import get_cognito
from djwarrant.forms import ProfileForm
from ..forms import SignUpForm, AccountVerificationForm
from warrant import Cognito
from djwarrant.backend import CognitoBackend
import boto3
import uuid
import json
from library.utils.dynamo_helpers import create_user


class TokenMixin(AccessMixin):

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('REFRESH_TOKEN'):
            return self.handle_no_permission()
        return super(TokenMixin, self).dispatch(
            request, *args, **kwargs)


class GetUserMixin(object):

    def get_user(self):
        c = get_cognito(self.request)
        return c.get_user(attr_map=settings.COGNITO_ATTR_MAPPING)


class ProfileView(LoginRequiredMixin, TokenMixin, GetUserMixin, TemplateView):
    template_name = 'warrant/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['user'] = self.get_user()
        return context


class UpdateProfileView(LoginRequiredMixin, TokenMixin, GetUserMixin, FormView):
    template_name = 'warrant/update-profile.html'
    form_class = ProfileForm

    def get_success_url(self):
        return reverse_lazy('dw:profile')

    def get_initial(self):
        u = self.get_user()
        return u.__dict__.get('_data')

    def form_valid(self, form):
        c = get_cognito(self.request)
        c.update_profile(form.cleaned_data, settings.COGNITO_ATTR_MAPPING)
        messages.success(
            self.request, 'You have successfully updated your profile.')
        return super(UpdateProfileView, self).form_valid(form)


class LogoutView(DJLogoutView):

    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.delete()
        return super(LogoutView, self).dispatch(request, *args, **kwargs)


class SignUpView(FormView):
    template_name = 'warrant/signup.html'
    form_class = SignUpForm

    def form_valid(self, form):
        cognito = CognitoBackend()

        try:
            # Register user to cognito
            resp = cognito.register(name=form.user['name'], password=form.user['password'],
                                    email=form.user['email'], username=form.user['username'])

            # Create user in DynamoDB
            create_user(id=resp['UserSub'], username=form.user['username'], name=form.user['name'],
                        email=form.user['email'], role="admin", library=form.user['library_name'])
        except Exception as e:
            if "User already exists" in str(e):
                form.errors['username'] = form.error_class(
                    ['The provided username is already in use'])
                return self.form_invalid(form)

            elif "Password did not conform with the policy" in str(e):
                forms.errors['username'] = form.error_class(
                    ['The password provided is invalid'])
                return self.form_invalid(form)

            else:
                raise(e)

        return HttpResponseRedirect(reverse('dw:account_verification',
                                            kwargs={'username': form.user['username']}))


class AccountVerificationView(FormView):
    template_name = 'warrant/account_verification.html'
    form_class = AccountVerificationForm

    def get_initial(self):
        initial = super().get_initial()
        initial['username'] = self.kwargs.get('username', '')

        return initial

    def get_success_url(self):
        return resolve_url('/')

    def form_valid(self, form):
        cognito = CognitoBackend()

        try:
            resp = cognito.validate_user(**form.user)
        except Exception as e:
            pass

        return super().form_valid(form)

djwarrant/views/storeinfo.py
from django.urls import reverse_lazy
from djwarrant.forms import StoreForm
from bootstrap_modal_forms.generic import BSModalCreateView
from bootstrap_modal_forms.forms import BSModalForm
from dynamodb_json import json_util as json
import json as og_json
from django.conf import settings
from django.shortcuts import render
import boto3
from boto3.dynamodb.conditions import Key
from bootstrap_modal_forms.forms import BSModalForm
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from djwarrant.forms import StoreForm
from django.urls import reverse_lazy
from django.http import HttpResponse


dynamodb = boto3.resource('dynamodb', region_name='us-east-1')
table = dynamodb.Table('stores')
# call dynamo from here


def storeinfo(request):
    store_id = request.user.email
    store_name = request.user.username

    resp = table.query(KeyConditionExpression=Key('id').eq(store_id))
    adult = resp['Items'][0]['adult']
    children = resp['Items'][0]['children']

    order_status = request.GET.get('status', 'all')
    orders = ViewOrders().process(store_id=store_id, status=order_status)

    return render(request,
                  'warrant/storeinfo.html',
                  {
                      'store_name': store_name,
                      'adult': adult,
                      'children': children,
                      'orders': orders,
                      'filter_status': order_status.capitalize()
                  })


class ViewOrders():
    """Loads Orders from DynamoDB"""

    def process(self, store_id=None, status='all'):
        index = 'store_id-index'
        queryCondition = 'store_id = :store_id'
        queryAttributes = {
            ':store_id': store_id
        }

        dynamoDB = boto3.client('dynamodb', region_name=settings.AWS_REGION)
        response = dynamoDB.query(
            TableName='orders',
            IndexName=index,
            KeyConditionExpression=queryCondition,
            ExpressionAttributeValues=og_json.loads(json.dumps(queryAttributes)))

        return filter_results(data=json.loads(response['Items']), status=status)


def filter_results(data, status='all'):
    if status == 'all':
        return data
    elif status == 'pending':
        return list(filter(lambda x: x['received'] == False, data))
    elif status == 'completed':
        return list(filter(lambda x: x['received'] == True, data))


class InventoryView(BSModalCreateView):
    template_name = 'warrant/update-inventory.html'
    form_class = StoreForm

    def get_success_url(self):
        if self.request.method == 'POST':
            form = StoreForm(self.request.POST)
            new_adult = form.data['adult_masks']
            new_children = form.data['children_masks']

            # send to dynamo
            store_id = self.request.user.email
            resp = table.query(KeyConditionExpression=Key('id').eq(store_id))

            try:
                update = table.update_item(
                    Key={"id": store_id},
                    UpdateExpression="set adult=:a, children=:c",
                    ExpressionAttributeValues={
                        ':a': new_adult,
                        ':c': new_children
                    },
                    ReturnValues="UPDATED_NEW"
                )
            except Exception as e:
                raise(e)

            print("Dynamo updated")

            sqs = boto3.client('sqs', region_name='us-east-1')
            qname = "https://sqs.us-east-1.amazonaws.com/583068504140/homework2"
            arn = resp['Items'][0]['sns_arn']
            name = resp['Items'][0]['name']

            # arn
            x = '''{{"function":"sendEmail", "store": "{0}", "adult": {1}, "children": {2}, "topic": "{3}"}}'''.format(
                name, new_adult, new_children, arn)
            sqs.send_message(QueueUrl=qname, MessageBody=x)
            print(x)
            print("sqs sent!")

        return reverse_lazy('dw:storeinfo')

    def get_initial(self):
        store_id = self.request.user.email
        resp = table.query(KeyConditionExpression=Key('id').eq(store_id))
        adult = resp['Items'][0]['adult']
        children = resp['Items'][0]['children']
        return {
            'adult_masks': adult,
            'children_masks': children
        }

djwarrant/views/subscriptions.py
import boto3
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin, \
    UserPassesTestMixin
from django.http import Http404
try:
    from django.urls import reverse_lazy
except ImportError:
    from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView
from django.views.generic.list import MultipleObjectMixin, ListView

from django.conf import settings
from warrant import UserObj, Cognito
from djwarrant.forms import APIKeySubscriptionForm


class GetCognitoUserMixin(object):
    client = boto3.client('apigateway', region_name="us-east-1")

    def get_user_object(self):
        cog_client = boto3.client('cognito-idp')
        user = cog_client.get_user(
            AccessToken=self.request.session['ACCESS_TOKEN'])
        u = UserObj(username=user.get('Username'),  # .get('UserAttributes')[0].get('username'),
                    attribute_list=user.get('UserAttributes'),
                    cognito_obj=cog_client,
                    attr_map=settings.COGNITO_ATTR_MAPPING)
        return u

    def get_queryset(self):
        try:
            u = self.get_user_object()
        except KeyError:
            raise Http404
        my_plans = self.client.get_usage_plans(keyId=u.api_key_id)
        return my_plans.get('items', [])


class MySubscriptions(LoginRequiredMixin, GetCognitoUserMixin, ListView):
    template_name = 'warrant/subscriptions.html'


class AdminListUsers(UserPassesTestMixin, ListView):
    template_name = 'warrant/admin-list-users.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_queryset(self):
        response = Cognito(settings.COGNITO_USER_POOL_ID, settings.COGNITO_APP_ID)\
            .get_users(attr_map=settings.COGNITO_ATTR_MAPPING)
        return response


class AdminSubscriptions(UserPassesTestMixin, GetCognitoUserMixin,
                         FormView):
    template_name = 'warrant/admin-subscriptions.html'
    form_class = APIKeySubscriptionForm

    def get_success_url(self):
        return reverse_lazy('dw:admin-cognito-user',
                            args=[self.kwargs.get('username')])

    def test_func(self):
        return self.request.user.has_perm('can_edit')

    def get_user_object(self):
        return Cognito(settings.COGNITO_USER_POOL_ID, settings.COGNITO_APP_ID,
                       username=self.kwargs.get('username')).admin_get_user(
            attr_map=settings.COGNITO_ATTR_MAPPING)

    def get_context_data(self, **kwargs):
        kwargs['object_list'] = self.object_list = self.get_queryset()
        context = super(AdminSubscriptions, self).get_context_data(**kwargs)
        return context

    def get_form_kwargs(self):
        kwargs = super(AdminSubscriptions, self).get_form_kwargs()
        kwargs.update({'plans': self.client.get_usage_plans().get('items', []),
                       'users_plans': [p.get('id') for p in self.get_queryset()]})
        return kwargs

    def form_invalid(self, form):

        return super(AdminSubscriptions, self).form_invalid(form)

    def form_valid(self, form):
        self.client.create_usage_plan_key(
            usagePlanId=form.cleaned_data['plan'],
            keyId=self.get_user_object().api_key_id,
            keyType='API_KEY'
        )
        messages.success(self.request, 'Addedd subscription successfully.')
        return super(AdminSubscriptions, self).form_valid(form)

djwarrant/templates/warrant/_header.html
{% load static %}

<nav class="header">
  <div class="header__title">
    <a href="{% url 'index' %}">
      <img src="{% static 'img/Smart Library (2).png' %}" alt="Smart Library logo with various 2d books" width="72px" height="72px"/>
    </a>
  </div>

  <ul class="header__items">
    {% if request.user.is_authenticated %}
    <li class="header__item">
      <a href="{% url 'dw:profile' %}">My Profile</a>
    </li>

    {% comment %} <li class="header__item">
      <a href="{% url 'dw:subscriptions' %}">My Subscriptions</a>
    </li> {% endcomment %}

    <li class="header__item">
      <a href="{% url 'book_index' %}">Books</a>
    </li>

    <li class="header__item">
      <a href="{% url 'dw:logout' %}">Logout</a>
    </li>
    {% else %}
    <li class="header__item"><a href="{% url 'dw:login' %}">Login</a></li>
    <li class="header__item"><a href="{% url 'dw:signup' %}">Sign Up</a></li>
    {% endif %}
  </ul>

  <div class="flex-right burger-header--wrapper">
    <div id="mainHeader" class="burger-header">
      <div class="bar__base bar-1"></div>
      <div class="bar__base bar-2"></div>
      <div class="bar__base bar-3"></div>
    </div>
  </div>
</nav>

<div id="main-header-links" class="collapsed-nav">
  {% if request.user.is_authenticated %}
    <li class="header__item">
      <a href="{% url 'dw:profile' %}" class="collapsed-header-link">My Profile</a>
    </li>

    {% comment %} <li>
      <a href="{% url 'dw:subscriptions' %}" class="collapsed-header-link">My Subscriptions</a>
    </li> {% endcomment %}

    <li>
      <a href="{% url 'book_index' %}" class="collapsed-header-link">Books</a>
    </li>

    <li>
      <a href="{% url 'dw:logout' %}" class="collapsed-header-link">Logout</a>
    </li>
  {% else %}
    <li><a href="{% url 'dw:login' %}" class="collapsed-header-link">Login</a></li>
    <li><a href="{% url 'dw:signup' %}" class="collapsed-header-link">Sign Up</a></li>
  {% endif %}
</div>

djwarrant/templates/warrant/account_verification.html
{% extends 'warrant/base.html' %}
{% load widget_tweaks %}

{% block title %} | Verify Account {% endblock title %}

{% block main_content %}
  <form method="post" class="user-session__form">
    <h1 class="user-session__heading user-session__form--title">Verify Account</h1>

    <p style="margin-bottom: 1em;">We sent a confirmation code to the email you provided. Please enter the code below to verify your account.</p>

    {% csrf_token %}
    {% for field in form %}
      <div class="user-session__input-group">
        {% comment %} {{ field.label_tag }}<br> {% endcomment %}
        <label class="user-session__input-group--label" for="{{ field.id_for_label }}">{{ field.name }}</label>

        {{ field|add_class:'user-session__input-group--input' }}


        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
          <div class="user-session__input-group--error">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    <button class="user-session__button" type="submit">Verify</button>
  </form>
{% endblock %}

djwarrant/templates/warrant/admin-list-users.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <table class="table">
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th></th>
        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.username}}</td>
            <td>{{ obj.first_name }}</td>
            <td>{{ obj.last_name }}</td>
            <td><a href="{% url 'dw:admin-cognito-user' obj.username %}" class="btn btn-success">View</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

djwarrant/templates/warrant/admin-subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}
    <h2>Current Subscriptions</h2>
    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>

    <h2>Add User to New Plan</h2>
    <form method='post' class="form">
  {% csrf_token %}
    <table class="table">
        {{ form.errors }}
  {{ form.as_table }}
        </table>
  <input type='submit' value='submit' />
</form>
{% endblock %}

djwarrant/templates/warrant/base.html
{% load static %}

<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>{% block title %}{% endblock %} | Mask Inventory</title>

  {% block css %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  {% endblock %}

  <script src="{% static 'js/header.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="main">
  {% include 'warrant/_header.html' %}

  {% block body %}
    {% block content %}
      <div class="container" id="main-container">
        <div class="row">

          <div class="col-md-12">
            {% block main_content %}

            {% endblock %}
          </div>
        </div>
      </div>
    {% endblock content %}
  {% endblock body %}

  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->

    {% block js %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock %}

    {% block scripts %}

      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}
  </body>
</html>

djwarrant/templates/warrant/login.html
{% extends 'warrant/base.html' %}
{% load widget_tweaks %}

{% block title %}Login{% endblock title %}

{% block main_content %}
  <form method="post" class="user-session__form">
    <h1 class="user-session__heading user-session__form--title">Login</h1>

    {% csrf_token %}
    {% for field in form %}
      <div class="user-session__input-group">
        {% comment %} {{ field.label_tag }}<br> {% endcomment %}
        <label class="user-session__input-group--label" for="{{ field.id_for_label }}">{{ field.name }}</label>

        {{ field|add_class:'user-session__input-group--input' }}


        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
          <div class="user-session__input-group--error">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    <button class="user-session__button" type="submit">Login</button>
  </form>
{% endblock %}

djwarrant/templates/warrant/logout.html
{% extends 'warrant/base.html' %}
{% load static %}
{% block title %}
  Logged Out
{% endblock %}

{% block extra_css %}
	<link href="{% static 'css/home.css' %}" rel="stylesheet"/>
{% endblock extra_css %}

{% block main_content %}
	<div class="bg-white container text-center">
		<img width="420px" src="{% static 'img/books.gif' %}" />
		<h1 class="text-center" style="margin-top: 1em"> <strong> You have been logged out! </strong> </h1>
	</div>
{% endblock %}

djwarrant/templates/warrant/profile.html
{% extends 'warrant/base.html' %}
{% load cognito_tags %}
{% load static %}


{% block title %}Your Profile{% endblock title %}

{% block main_content %}
<div class = "row">
  <div class = "col-md-2"> </div>
  <div class = "col-md-8">
  <div class = "row"> <img src="{% static 'img/profile.jpg' %}" style="max-width: 100%" /> </div>

  <div class = "row" style = "box-shadow: 0 1rem 3rem rgba(0,0,0,.175)!important">

  <div class="user-session__content-wrapper">
    <div style="display: flex; align-items: baseline; justify-content: space-between;">
      <h1 class="user-session__heading"> <strong> {{ user|username }} </strong> </h1>
      <a href="{% url 'dw:update-profile' %}">Edit</a>
    </div>

    <div>
      <div class="profile__detail-group">
        <h4 class="profile__detail-group--label">
          Username
        </h4>

        <span>
          {{ user|username }}
        </span>
      </div>

      <div class="profile__detail-group">
        <h4 class="profile__detail-group--label">
          Name
        </h4>

        <span>
          {{ user.name }}
        </span>
      </div>

      <div class="profile__detail-group">
        <h4 class="profile__detail-group--label">
          Email
        </h4>

        <span>
          {{ user.email }}
        </span>
      </div>

      <div class="profile__detail-group">
        <h4 class="profile__detail-group--label">
          Address
        </h4>

        <span>
          {{ user.address }}
        </span>
      </div>
    </div>
  </div>

</div>

</div>
<div class = "col-md-2"> </div>
</div>
{% endblock main_content %}

djwarrant/templates/warrant/signup.html
{% extends 'warrant/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Sign Up{% endblock title %}

{% block main_content %}

<div class = "col-md-6">
  <form method="post" class="user-session__form">
    <h1 class="user-session__heading user-session__form--title">Sign up</h1>

    {% csrf_token %}
    {% for field in form %}
      <div class="user-session__input-group">
        {% comment %} {{ field.label_tag }}<br> {% endcomment %}
        <label class="user-session__input-group--label" for="{{ field.id_for_label }}">{{ field.name }}</label>

        {{ field|add_class:'user-session__input-group--input' }}


        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
          <div class="user-session__input-group--error">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    <button class="user-session__button" type="submit">Sign up</button>
  </form>
</div>

<div class = "col-md-6" style = "padding-top: 20px">
  <img src="{% static 'img/02.svg' %}" style="max-width: 90%" />
  <img src="{% static 'img/06.svg' %}" style="max-width: 90%" />

</div>
{% endblock %}

djwarrant/templates/warrant/subscriptions.html
{% extends 'warrant/base.html' %}

{% block main_content %}

    <table class="table">
        <tr>
            <th>Plan Name</th>
            <th>Description</th>

        </tr>
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.description }}</td>

        </tr>
    {% endfor %}
    </table>
{% endblock %}